### ISSUE TITLE
Find/Create odom messages for atlascar2 ackermann simulation

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atlascar2#26]
In order to work with odometry in simulation, odom messages need to exist.

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira!
While looking with @Sarxell through the current simulation, we found out that it works using position/velocity controllers for various joints. One example can be seen here:
https://github.com/lardemua/atlascar2/blob/753c6a6085113d227ccbb150185c5cd9feebc62d/atlascar2_description/config/atlascar2_joint_ctrlr_params.yaml#L32-L35
These controllers have messages of the type `control_msgs/JointControllerState`. An example can be seen here:

```sh
---
header: 
  seq: 796
  stamp: 
    secs: 2514
    nsecs: 998000000
  frame_id: ''
set_point: 0.0
process_value: -2.8604798222531258e-05
process_value_dot: 0.0016250648709078689
error: 2.8604798222531258e-05
time_step: 0.001
command: -0.005754577306568365
p: 4.0
i: 0.0
d: 1.0
i_clamp: 0.0
antiwindup: False
```
Using the process_value we can have an estimate of the position of that link. Using the position of the steering and traction links, we can implement a node that calculates the kinematics and can publish an odometry message. This might be complicated and time-consuming.

Another option found was to restructure the way the vehicle controls in gazebo. There exists a controller named [ackermann_steering_controller](http://wiki.ros.org/action/fullsearch/ackermann_steering_controller?action=fullsearch&context=180&value=linkto%3A%22ackermann_steering_controller%22), which is fairly more straight forward. An example can be seen [here](https://github.com/CIR-KIT-Unit03/cirkit_unit03_common/blob/master/cirkit_unit03_control/config/cirkit_unit03_steer_drive_controller_gazebo.yaml). An excerpt can be found here.

```yaml
# Wheel & Steer
steer_drive_controller:
  type                          : "steer_drive_controller/SteerDriveController"
  rear_wheel                    : 'rear_wheel_joint'
  front_steer                   : 'front_steer_joint'
  #publish_rate                  : 100

  pose_covariance_diagonal      : [0.00001, 0.00001, 1000000000000.0, 1000000000000.0, 1000000000000.0, 0.001]
  twist_covariance_diagonal     : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  wheel_separation_h_multiplier : 1.7 # calibration parameter for angle odometory
  #wheel_radius_multiplier       : 1.0 # calibration parameter for linear odometory
  steer_pos_multiplier          : 1.5
  cmd_vel_timeout               : 4
  base_frame_id                 : base_link

  enable_odom_tf: true
```
It only uses one controller and it publishes the odom messages directly. However, the counterpoint is that the xacro model of the robot needs to be redone. It should be similar to something like [this](https://github.com/CIR-KIT-Unit03/cirkit_unit03_common/blob/master/cirkit_unit03_description/urdf/cirkit_unit03_macro.xacro).

I believe Sara will share another two options. Any help from the professor regarding which option should he choose would be greatly appreciated.

Thank you and have a nice weekend.
