### ISSUE TITLE
Odometry drift in ackermann controller

### ISSUE THREAD

**Issue by Sarxell** [lardemua/atlascar2#37]
Hi @miguelriemoliveira ,
Doing tests with the two odometries I came across a problem. Since the robot drifts in gazebo, the odometry from the ackermann controller also drifts which in the long time gets a very different value from the odometry of the python code.
The values in question:

**Python odometry**
```
pose: 
  pose: 
    position: 
      x: 33.52832900205622
      y: 0.0
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
...
twist: 
  twist: 
    linear: 
      x: 0.0
      y: 0.0
      z: 0.0
    angular: 
      x: 0.0
      y: 0.0
      z: 0.0
```

**ackermann controller odometry**

```
pose: 
  pose: 
    position: 
      x: 33.518611540783525
      y: -0.01387301223711008
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.00020072386327466468
      w: 0.9999999798549651
...
twist: 
  twist: 
    linear: 
      x: -1.9479035983982484e-05
      y: 0.0
      z: 0.0
    angular: 
      x: 0.0
      y: 0.0
      z: 4.910143044064103e-12
```

What should I do? 

- Improving the urdf model with the inertia and mass which is what some answers tell me to check.
https://answers.gazebosim.org//question/12952/robot-base-slowly-drifting/
https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/149

- Should I add drift in the python code? Doesn't seem very possible but I know the real car also drifts

-Should I leave it? With this the values in the long term become imprecise...

**Comment by Sarxell** [comment]
With inertial values tending to infinite (in this case `1000000000000.0`) we get values like this:
```
pose: 
  pose: 
    position: 
      x: 35.28116784527102
      y: 1.924409111229197e-09
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -2.640759797793107e-09
      w: 1.0
...
twist: 
  twist: 
    linear: 
      x: 2.1270807115669754e-08
      y: 0.0
      z: 0.0
    angular: 
      x: 0.0
      y: 0.0
      z: 8.226988294801665e-10

```

But I can use real values (mass, the inertia formula) which gives us a value more realist ... 
Do I use the real value, compare with the no-drift odometry? Do I try to find a formula which can gives us the car drift to more precise results?
